version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3002:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    environment:
      - PORT=3002
    depends_on: #only mongo started only node-app start
      - mongo
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo123
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db: